In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Boston.csv')
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,NaN,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,NaN,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [3]:
df.drop(columns=['B'],inplace=True)

In [4]:
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
LSTAT      20
MEDV        0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  LSTAT    486 non-null    float64
 12  MEDV     506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB

In [6]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,LSTAT,MEDV
count,486.000000,486.000000,486.000000,486.000000,506.000000,506.000000,486.000000,506.000000,506.000000,506.000000,506.000000,486.000000,506.000000
mean,3.611874,11.211934,11.083992,0.069959,0.554695,6.284634,68.518519,3.795043,9.549407,408.237154,18.455534,12.715432,22.532806
std,8.720192,23.388876,6.835896,0.255340,0.115878,0.702617,27.999513,2.105710,8.707259,168.537116,2.164946,7.155871,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,1.730000,5.000000
25%,0.081900,0.000000,5.190000,0.000000,0.449000,5.885500,45.175000,2.100175,4.000000,279.000000,17.400000,7.125000,17.025000
50%,0.253715,0.000000,9.690000,0.000000,0.538000,6.208500,76.800000,3.207450,5.000000,330.000000,19.050000,11.430000,21.200000
75%,3.560263,12.500000,18.100000,0.000000,0.624000,6.623500,93.975000,5.188425,24.000000,666.000000,20.200000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,37.970000,50.000000

In [7]:
df.corr()['MEDV'].sort_values()

LSTAT     -0.735822
PTRATIO   -0.507787
INDUS     -0.481772
TAX       -0.468536
NOX       -0.427321
AGE       -0.394656
CRIM      -0.391363
RAD       -0.381626
CHAS       0.181391
DIS        0.249929
ZN         0.373136
RM         0.695360
MEDV       1.000000
Name: MEDV, dtype: float64

In [8]:
X = df.loc[:,['LSTAT','PTRATIO','RM']]
Y = df.loc[:,"MEDV"]
X.shape,Y.shape

((506, 3), (506,))

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=10)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(x_train)

StandardScaler()

In [13]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Input

In [15]:
model = Sequential()

In [16]:
model.add(Input(shape=(3,), name='input'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64,activation='relu',name='layer_1'))
model.add(Dense(1,activation='linear',name='output'))
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output (Dense)                       │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,833 (34.50 KB)

 Trainable params: 8,833 (34.50 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.fit(x_train,y_train,epochs=100,validation_split=0.05)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 547.6071 - mae: 21.7514 - val_loss: 736.2436 - val_mae: 24.5070
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 544.4636 - mae: 21.6803 - val_loss: 731.9852 - val_mae: 24.4199
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 540.4748 - mae: 21.5882 - val_loss: 727.1087 - val_mae: 24.3199
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 535.8412 - mae: 21.4802 - val_loss: 721.3332 - val_mae: 24.2008
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 530.3318 - mae: 21.3529 - val_loss: 714.6011 - val_mae: 24.0613
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 524.0054 - mae: 21.2030 - val_loss: 706.7553 - val_mae: 23.8977
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 516.6802 - mae: 21.0304 - val_loss: 697.9133 - val_mae: 23.7120
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 508.4587 - mae: 20.8335 - val_loss: 687.9224 - val_mae: 23.5004
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 499.2102 - mae: 20.6116 - val_loss: 676.8729 - val_mae: 23.2641
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 489.1840 - mae: 20.3621 - val_loss: 664.6579 - val_mae: 23.0001
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 478.1312 - mae: 20.0898 - val_loss: 651.5826 - val_mae: 22.7141
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 466.1406 - mae: 19.7933 - val_loss: 637.5502 - val_mae: 22.4031
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 453.5726 - mae: 19.4697 - val_loss: 622.5001 - val_mae: 22.0646
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 440.1758 - mae: 19.1220 - val_loss: 606.7897 - val_mae: 21.7057
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 426.2737 - mae: 18.7562 - val_loss: 590.5516 - val_mae: 21.3284
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 412.0078 - mae: 18.3677 - val_loss: 573.5871 - val_mae: 20.9269
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 397.1102 - mae: 17.9563 - val_loss: 556.0962 - val_mae: 20.5047
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 381.7563 - mae: 17.5321 - val_loss: 538.5101 - val_mae: 20.0713
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 366.3773 - mae: 17.0882 - val_loss: 520.4319 - val_mae: 19.6158
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 350.6266 - mae: 16.6226 - val_loss: 501.6070 - val_mae: 19.1299
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 334.6095 - mae: 16.1359 - val_loss: 482.7921 - val_mae: 18.6317
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 318.6728 - mae: 15.6396 - val_loss: 463.9945 - val_mae: 18.1202
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 302.8234 - mae: 15.1363 - val_loss: 445.4239 - val_mae: 17.6003
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 287.3673 - mae: 14.6241 - val_loss: 427.0098 - val_mae: 17.0692
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 271.9020 - mae: 14.1131 - val_loss: 409.1181 - val_mae: 16.5368
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 256.7149 - mae: 13.6057 - val_loss: 391.2638 - val_mae: 16.0401
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 242.2761 - mae: 13.0864 - val_loss: 373.4976 - val_mae: 15.5340
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 227.8816 - mae: 12.5689 - val_loss: 356.5399 - val_mae: 15.0330
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 214.3913 - mae: 12.0642 - val_loss: 339.9130 - val_mae: 14.5227
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 201.2784 - mae: 11.5693 - val_loss: 324.1401 - val_mae: 14.0191
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 188.8913 - mae: 11.0991 - val_loss: 309.4254 - val_mae: 13.5299
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 177.4323 - mae: 10.6201 - val_loss: 294.6231 - val_mae: 13.0163
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 166.2993 - mae: 10.1692 - val_loss: 281.0840 - val_mae: 12.5252
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 156.0580 - mae: 9.7298 - val_loss: 268.1163 - val_mae: 12.0330
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 146.3965 - mae: 9.3297 - val_loss: 256.2633 - val_mae: 11.6143
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 138.0038 - mae: 8.9540 - val_loss: 244.7012 - val_mae: 11.1882
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 129.7640 - mae: 8.6166 - val_loss: 234.4056 - val_mae: 10.7894
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 122.5188 - mae: 8.3128 - val_loss: 225.1194 - val_mae: 10.4114
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 116.2267 - mae: 8.0390 - val_loss: 216.2530 - val_mae: 10.0317
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 110.2403 - mae: 7.7855 - val_loss: 208.0083 - val_mae: 9.6595
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 105.1280 - mae: 7.5512 - val_loss: 200.7684 - val_mae: 9.3388
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 100.5586 - mae: 7.3499 - val_loss: 194.4820 - val_mae: 9.1421
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 96.8068 - mae: 7.1662 - val_loss: 188.7437 - val_mae: 9.0008
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 93.2434 - mae: 6.9863 - val_loss: 183.5756 - val_mae: 8.9048
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 90.3032 - mae: 6.8381 - val_loss: 178.3895 - val_mae: 8.8035
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 87.4905 - mae: 6.6917 - val_loss: 174.2189 - val_mae: 8.7174
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 85.2509 - mae: 6.5729 - val_loss: 170.4613 - val_mae: 8.6357
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 83.2245 - mae: 6.4738 - val_loss: 167.2145 - val_mae: 8.5615
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 81.6223 - mae: 6.3947 - val_loss: 163.9314 - val_mae: 8.4825
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 80.3371 - mae: 6.3309 - val_loss: 160.9766 - val_mae: 8.4074
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 79.0356 - mae: 6.2763 - val_loss: 158.9158 - val_mae: 8.3524
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 78.1575 - mae: 6.2360 - val_loss: 156.7306 - val_mae: 8.3011
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 77.3976 - mae: 6.2102 - val_loss: 154.9110 - val_mae: 8.2691
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 76.7882 - mae: 6.1959 - val_loss: 153.3171 - val_mae: 8.2398
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 76.2660 - mae: 6.1881 - val_loss: 152.0737 - val_mae: 8.2160
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 75.8635 - mae: 6.1836 - val_loss: 150.8196 - val_mae: 8.2005
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 75.5447 - mae: 6.1840 - val_loss: 149.8091 - val_mae: 8.1936
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 75.3077 - mae: 6.1850 - val_loss: 148.9800 - val_mae: 8.1877
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 75.1093 - mae: 6.1860 - val_loss: 148.4383 - val_mae: 8.1838
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.9961 - mae: 6.1961 - val_loss: 147.5494 - val_mae: 8.1771
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.8266 - mae: 6.1975 - val_loss: 146.9890 - val_mae: 8.1728
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.7542 - mae: 6.2052 - val_loss: 146.4807 - val_mae: 8.1688
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.6681 - mae: 6.2081 - val_loss: 146.2513 - val_mae: 8.1669
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.6250 - mae: 6.2143 - val_loss: 145.6280 - val_mae: 8.1645
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.5563 - mae: 6.2195 - val_loss: 145.3534 - val_mae: 8.1668
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.5140 - mae: 6.2245 - val_loss: 145.0266 - val_mae: 8.1696
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4905 - mae: 6.2303 - val_loss: 144.7329 - val_mae: 8.1722
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4881 - mae: 6.2372 - val_loss: 144.3804 - val_mae: 8.1753
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 74.4640 - mae: 6.2409 - val_loss: 144.2456 - val_mae: 8.1765
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4579 - mae: 6.2422 - val_loss: 144.2133 - val_mae: 8.1768
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4455 - mae: 6.2434 - val_loss: 144.0750 - val_mae: 8.1780
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4508 - mae: 6.2461 - val_loss: 143.9738 - val_mae: 8.1789
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4540 - mae: 6.2514 - val_loss: 143.6708 - val_mae: 8.1873
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4534 - mae: 6.2606 - val_loss: 143.4226 - val_mae: 8.1942
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 74.4470 - mae: 6.2639 - val_loss: 143.3207 - val_mae: 8.1971
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4469 - mae: 6.2643 - val_loss: 143.3423 - val_mae: 8.1965
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4445 - mae: 6.2655 - val_loss: 143.2668 - val_mae: 8.1987
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 74.4452 - mae: 6.2655 - val_loss: 143.2680 - val_mae: 8.1986
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4341 - mae: 6.2632 - val_loss: 143.4288 - val_mae: 8.1941
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 74.4354 - mae: 6.2620 - val_loss: 143.3778 - val_mae: 8.1955
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4438 - mae: 6.2621 - val_loss: 143.3867 - val_mae: 8.1952
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4564 - mae: 6.2575 - val_loss: 143.6551 - val_mae: 8.1877
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 74.4756 - mae: 6.2638 - val_loss: 143.2334 - val_mae: 8.1996
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4391 - mae: 6.2676 - val_loss: 143.1355 - val_mae: 8.2024
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4462 - mae: 6.2703 - val_loss: 143.1047 - val_mae: 8.2033
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4580 - mae: 6.2732 - val_loss: 143.0309 - val_mae: 8.2055
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4624 - mae: 6.2679 - val_loss: 143.3793 - val_mae: 8.1955
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4404 - mae: 6.2599 - val_loss: 143.5385 - val_mae: 8.1910
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4436 - mae: 6.2556 - val_loss: 143.6930 - val_mae: 8.1866
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4420 - mae: 6.2578 - val_loss: 143.4331 - val_mae: 8.1939
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4525 - mae: 6.2641 - val_loss: 143.3059 - val_mae: 8.1975
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4375 - mae: 6.2647 - val_loss: 143.3055 - val_mae: 8.1976
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4404 - mae: 6.2653 - val_loss: 143.2829 - val_mae: 8.1982
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4383 - mae: 6.2626 - val_loss: 143.4619 - val_mae: 8.1931
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4397 - mae: 6.2615 - val_loss: 143.4240 - val_mae: 8.1942
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 74.4376 - mae: 6.2613 - val_loss: 143.4528 - val_mae: 8.1934
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4510 - mae: 6.2584 - val_loss: 143.5915 - val_mae: 8.1895
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4574 - mae: 6.2619 - val_loss: 143.3475 - val_mae: 8.1964
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4426 - mae: 6.2614 - val_loss: 143.4944 - val_mae: 8.1922
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 74.4375 - mae: 6.2599 - val_loss: 143.4557 - val_mae: 8.1933

In [18]:
output = model.evaluate(x_test,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 106.0867 - mae: 7.1327

In [19]:
print(f"Mean Squared Error: {output[0]}"
      ,f"Mean Absolute Error: {output[1]}",sep="\n")

Mean Squared Error: 106.08670043945312
Mean Absolute Error: 7.132719039916992

In [20]:
y_pred = model.predict(x=x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

In [21]:
print(*zip(y_pred,y_test))

(array([21.790863], dtype=float32), 28.4) (array([21.790863], dtype=float32), 31.1) (array([21.790863], dtype=float32), 23.5) (array([21.790863], dtype=float32), 26.6) (array([21.790863], dtype=float32), 19.6) (array([21.790863], dtype=float32), 14.3) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 14.3) (array([21.790863], dtype=float32), 20.7) (array([21.790863], dtype=float32), 37.6) (array([21.790863], dtype=float32), 20.4) (array([21.790863], dtype=float32), 27.5) (array([21.790863], dtype=float32), 36.2) (array([21.790863], dtype=float32), 32.0) (array([21.790863], dtype=float32), 33.1) (array([21.790863], dtype=float32), 48.8) (array([21.790863], dtype=float32), 24.6) (array([21.790863], dtype=float32), 26.4) (array([21.790863], dtype=float32), 23.2) (array([21.790863], dtype=float32), 17.0) (array([21.790863], dtype=float32), 41.3) (array([21.790863], dtype=float32), 14.9) (array([21.790863], dtype=float32), 18.5) (array([21.790863], dtype=float32), 25.0) (array([21.790863], dtype=float32), 36.4) (array([21.790863], dtype=float32), 19.5) (array([21.790863], dtype=float32), 27.1) (array([21.790863], dtype=float32), 14.9) (array([21.790863], dtype=float32), 46.0) (array([21.790863], dtype=float32), 17.9) (array([21.790863], dtype=float32), 30.3) (array([21.790863], dtype=float32), 31.6) (array([21.790863], dtype=float32), 23.1) (array([21.790863], dtype=float32), 24.7) (array([21.790863], dtype=float32), 16.7) (array([21.790863], dtype=float32), 18.3) (array([21.790863], dtype=float32), 8.4) (array([21.790863], dtype=float32), 37.3) (array([21.790863], dtype=float32), 22.1) (array([21.790863], dtype=float32), 22.0) (array([21.790863], dtype=float32), 46.7) (array([21.790863], dtype=float32), 30.1) (array([21.790863], dtype=float32), 12.1) (array([21.790863], dtype=float32), 29.1) (array([21.790863], dtype=float32), 16.6) (array([21.790863], dtype=float32), 23.9) (array([21.790863], dtype=float32), 19.9) (array([21.790863], dtype=float32), 21.4) (array([21.790863], dtype=float32), 45.4) (array([21.790863], dtype=float32), 15.6) (array([21.790863], dtype=float32), 22.7) (array([21.790863], dtype=float32), 12.5) (array([21.790863], dtype=float32), 24.3) (array([21.790863], dtype=float32), 43.8) (array([21.790863], dtype=float32), 22.0) (array([21.790863], dtype=float32), 33.8) (array([21.790863], dtype=float32), 19.3) (array([21.790863], dtype=float32), 22.6) (array([21.790863], dtype=float32), 16.1) (array([21.790863], dtype=float32), 15.0) (array([21.790863], dtype=float32), 19.6) (array([21.790863], dtype=float32), 21.2) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 29.4) (array([21.790863], dtype=float32), 17.8) (array([21.790863], dtype=float32), 22.8) (array([21.790863], dtype=float32), 8.8) (array([21.790863], dtype=float32), 32.5) (array([21.790863], dtype=float32), 42.8) (array([21.790863], dtype=float32), 12.6) (array([21.790863], dtype=float32), 28.6) (array([21.790863], dtype=float32), 19.1) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 27.5) (array([21.790863], dtype=float32), 23.7) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 7.2) (array([21.790863], dtype=float32), 18.7) (array([21.790863], dtype=float32), 37.0) (array([21.790863], dtype=float32), 22.9) (array([21.790863], dtype=float32), 22.9) (array([21.790863], dtype=float32), 17.1) (array([21.790863], dtype=float32), 22.0) (array([21.790863], dtype=float32), 23.6) (array([21.790863], dtype=float32), 23.9) (array([21.790863], dtype=float32), 27.1) (array([21.790863], dtype=float32), 29.0) (array([21.790863], dtype=float32), 22.2) (array([21.790863], dtype=float32), 7.0) (array([21.790863], dtype=float32), 20.7) (array([21.790863], dtype=float32), 18.5) (array([21.790863], dtype=float32), 21.6) (array([21.790863], dtype=float32), 23.0) (array([21.790863], dtype=float32), 16.0) (array([21.790863], dtype=float32), 15.0) (array([21.790863], dtype=float32), 23.9) (array([21.790863], dtype=float32), 24.4) (array([21.790863], dtype=float32), 22.6) (array([21.790863], dtype=float32), 19.8) (array([21.790863], dtype=float32), 22.2) (array([21.790863], dtype=float32), 18.6) (array([21.790863], dtype=float32), 19.7) (array([21.790863], dtype=float32), 23.1) (array([21.790863], dtype=float32), 13.5) (array([21.790863], dtype=float32), 21.2) (array([21.790863], dtype=float32), 23.1) (array([21.790863], dtype=float32), 13.6) (array([21.790863], dtype=float32), 22.8) (array([21.790863], dtype=float32), 18.2) (array([21.790863], dtype=float32), 13.1) (array([21.790863], dtype=float32), 23.2) (array([21.790863], dtype=float32), 22.8) (array([21.790863], dtype=float32), 25.1) (array([21.790863], dtype=float32), 18.9) (array([21.790863], dtype=float32), 10.9) (array([21.790863], dtype=float32), 19.3) (array([21.790863], dtype=float32), 17.4) (array([21.790863], dtype=float32), 15.6) (array([21.790863], dtype=float32), 20.6) (array([21.790863], dtype=float32), 50.0) (array([21.790863], dtype=float32), 32.7) (array([21.790863], dtype=float32), 21.8) (array([21.790863], dtype=float32), 13.4) (array([21.790863], dtype=float32), 16.6) (array([21.790863], dtype=float32), 23.6) (array([21.790863], dtype=float32), 11.0)